#ifndef _MICROCDR_CONFIG_H_
#define _MICROCDR_CONFIG_H_

#define MICROCDR_VERSION_MAJOR 2
#define MICROCDR_VERSION_MINOR 0
#define MICROCDR_VERSION_MICRO 2
#define MICROCDR_VERSION_STR "2.0.2"

/* Xtensa (ESP32) is little-endian */
#define UCDR_MACHINE_ENDIANNESS UCDR_LITTLE_ENDIANNESS

#endif // _MICROCDR_CONFIG_H_
